language: java
sudo: no
env:
  - MAVEN_VERSION=3.0.5
  - MAVEN_VERSION=3.3.9
  - MAVEN_VERSION=3.5.4
  - MAVEN_VERSION=3.6.3
jdk:
  - openjdk8
  - openjdk11
install:
  - "mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN_VERSION}"
  - "./mvnw --show-version --errors --batch-mode test-compile dependency:go-offline"
script: "./mvnw --show-version --errors --batch-mode clean verify site"
cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
